# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/openjdk:jdk
  environment:
    MAVEN_OPTS: -Xmx3200m

jobs:
  test:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn clean package -DskipTests=true

  deploy:
    <<: *defaults

    steps:
      - run: mvn -s .circleci/.settings.xml -Prelease -Dmaven.test.skip=true deploy

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
#          filters:
#            tags:
#              only: /^\d+\.\d+\.\d+$/
      - deploy
#            requires:
#              - test
#            filters:
#              branches:
#                ignore: /.*/
#              tags:
#                only: /^\d+\.\d+\.\d+$/
